language: java
jdk:
- openjdk11
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_05569c8d5f8c_key -iv $encrypted_05569c8d5f8c_iv
  -in application-sentry.yml.enc -out application-sentry.yml -d
- openssl aes-256-cbc -K $encrypted_2e8be43b8f53_key -iv $encrypted_2e8be43b8f53_iv
  -in application-oauth.yml.enc -out application-oauth.yml -d
- openssl aes-256-cbc -K $encrypted_00ae6c5e2188_key -iv $encrypted_00ae6c5e2188_iv
  -in application-git.yml.enc -out application-git.yml -d
- openssl aes-256-cbc -K $encrypted_36fa70e438b7_key -iv $encrypted_36fa70e438b7_iv
  -in application-aws.yml.enc -out application-aws.yml -d
- openssl aes-256-cbc -K $encrypted_d8f3cd46c62c_key -iv $encrypted_d8f3cd46c62c_iv
  -in application-db.yml.enc -out application-db.yml -d
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - jyh4358@gmail.com
