language: java
jdk:
- openjdk11
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_a347c6e75b17_key -iv $encrypted_a347c6e75b17_iv
  -in application-key.yml.enc -out src/main/resources/application-key.yml -d
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - jyh4358@gmail.com
