language: java
jdk:
- openjdk11
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_51962345a7ea_key -iv $encrypted_51962345a7ea_iv
  -in application-db.yml.enc -out src/main/resources/application-db.yml -d
- openssl aes-256-cbc -K $encrypted_f549d91b60ba_key -iv $encrypted_f549d91b60ba_iv
  -in application-sentry.yml.enc -out src/main/resources/application-sentry.yml -d
- openssl aes-256-cbc -K $encrypted_8407c44c2dc8_key -iv $encrypted_8407c44c2dc8_iv
  -in application-aws.yml.enc -out src/main/resources/application-aws.yml -d
- openssl aes-256-cbc -K $encrypted_b10d9d709ee2_key -iv $encrypted_b10d9d709ee2_iv
  -in application-git.yml.enc -out src/main/resources/application-git.yml -d
- openssl aes-256-cbc -K $encrypted_0970f69e32ca_key -iv $encrypted_0970f69e32ca_iv
  -in application-oauth.yml.enc -out src/main/resources/application-oauth.yml -d
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - jyh4358@gmail.com
